### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by lalagreen** [pfirpfel/node-exclusive-keyboard#3]
C:\Users\STEPHEN\Desktop\node-exclusive-keyboard-master>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.16.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\STEPHEN\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.1216) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\STEPHEN\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\STEPHEN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\STEPHEN\\Desktop\\node-exclusive-keyboard-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\STEPHEN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\STEPHEN\\AppData\\Local\\node-gyp\\Cache\\12.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\STEPHEN\\AppData\\Local\\node-gyp\\Cache\\12.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\STEPHEN\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\STEPHEN\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\STEPHEN\\Desktop\\node-exclusive-keyboard-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\STEPHEN\\Desktop\\node-exclusive-keyboard-master\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  eviocgrab.cpp
  win_delay_load_hook.cc
c:\users\stephen\desktop\node-exclusive-keyboard-master\lib\eviocgrab.cpp(2)
: fatal error C1083: Cannot open include file: 'sys/ioctl.h': No such file o
r directory [C:\Users\STEPHEN\Desktop\node-exclusive-keyboard-master\build\e
viocgrab.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\STEPHEN\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\STEPHEN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\STEPHEN\Desktop\node-exclusive-keyboard-master
gyp ERR! node -v v12.16.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok

**Comment by pfirpfel** [comment]
This is not supposed to work on Windows.
